

production:
  adapter: mysql2
  database: movie_review
  server: localhost
  host: localhost
  port: 3306
  username: root
  password: root
  encoding: utf8
  reconnect: true

development:
  adapter: mysql2
  database: movie_review
  server: localhost
  host: localhost
  port: 3306
  username: root
  password: root
  encoding: utf8
  reconnect: true


test:
  adapter: mysql2
  database: movie_review
  host: localhost
  username: root
  password: root
  encoding: utf8

